In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.1


In [3]:
zeros = np.array([10])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
np.ones([3,5], dtype=np.int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.ones([3,2], dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
x = np.arange(4, dtype=np.int)

In [9]:
np.ones_like(x)

array([1, 1, 1, 1])

In [10]:
x = np.ones([3,5], dtype=np.int)
np.ones_like(x)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.ones([4,4],dtype=np.int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [12]:
x = np.ones([3,5], dtype = np.int)

np.ones_like(x) * 7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.randint(10, size=3)

array([7, 1, 2])

In [15]:
np.random.randn(3,3,3)

array([[[-0.82958862,  0.37441221, -0.07972555],
        [-0.41457503, -1.49037124,  0.08070377],
        [-0.40601678, -1.93938162,  2.72473858]],

       [[-0.99350042,  0.9629249 ,  0.2438653 ],
        [ 1.10803921,  1.54069116,  1.92513756],
        [ 0.27187612, -1.34652268,  0.01344179]],

       [[ 0.91304832, -0.60933458,  1.37257705],
        [-1.84559172,  0.13491544, -0.98888697],
        [ 0.32438342, -0.09468219, -0.57790451]]])

In [16]:
x = [1,2,3,4,5]
np.array(x)

array([1, 2, 3, 4, 5])

In [17]:
x = np.array([2,4,5,6])
y = x
y

array([2, 4, 5, 6])

In [18]:
y = np.copy(x)
y

array([2, 4, 5, 6])

In [19]:
x

array([2, 4, 5, 6])

In [20]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [22]:
np.arange(1,10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [23]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
z = np.zeros([3,3])
print("%d bytes" % (z.size * z.itemsize))

72 bytes


In [25]:
x = np.array(['A','B','C','D','E'])
x[0]

'A'

In [26]:
x = np.array(['A','B','C','D','E'])
x[-1]

'E'

In [27]:
x = np.array(['A','B','C','D','E'])
x[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [28]:
x = np.array(['A','B','C','D','E','T'])
x = x[1:-1]
x

array(['B', 'C', 'D', 'E'], dtype='<U1')

In [29]:
x = np.array(['A','B','C','D','E'])
x[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [30]:
x = np.array(['A','B','C','D','E'])
x[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [31]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[0]

array([1, 2, 3])

In [32]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[-1]

array([7, 8, 9])

In [33]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[0][0]

1

In [34]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[-1][-1]

9

In [35]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[1:-1, 1:-1]

array([[5]])

In [36]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[:2,:2]

array([[1, 2],
       [4, 5]])

In [37]:
x = [-5, -3, 0, 10, 40]
a = np.array(x, dtype=np.float)

In [38]:
a[::-1]

array([40., 10.,  0., -3., -5.])

In [39]:
x = np.array([-5, 20, 10, 1, 40])
x.sort()
x

array([-5,  1, 10, 20, 40])

In [40]:

X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [41]:
x = np.array([-5, 20, 10, 1, 40])
x[3] = 50

In [42]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = np.array([1,1,1,1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [43]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [44]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [45]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask


array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [46]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X < 0
X[mask]

array([-1, -4, -9])

In [47]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X > 5
X[mask]

array([ 6, 10])

In [48]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X > X.mean()
X[mask]


array([ 2,  5,  6, 10])

In [49]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

In [50]:
X = np.array([-1,2,-4,5,6,-9,10])
X.all()

True

In [51]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X.any()

True

In [52]:
X = np.array([[1,2,3],[3,5,1]])
X.sum()

15

In [53]:
X.mean()

2.5

In [54]:
X.sum(axis=1) # remember: axis=0 columns; axis=1 rows

array([6, 9])

In [55]:
X.mean(axis=0) # remember: axis=0 columns; axis=1 rows

array([2. , 3.5, 2. ])

In [56]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10